language: c

env:
  - PYTHON_VERSION=3.7

matrix:
  include:
      # Linux
      - os: linux
        name: "Linux full"
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - libopenmpi-dev
              - openmpi-bin
      # OSX
      - os: osx
        name: "MacOS full"


before_install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ${HOME}/miniconda
  - export PATH=${HOME}/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:
    - install_prefix=~
    - conda create -n testenv --yes pip python=${PYTHON_VERSION}
    - source activate testenv
    - conda install --yes scipy numpy matplotlib
    - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        conda install --yes mpi4py openmpi
      else
        pip install mpi4py
      fi
    - pip install flake8 pytest pytest-cov
    - pip install mne psutil joblib
    - pip install coverage coveralls
    - pip install NEURON
    - |
      cd $TRAVIS_BUILD_DIR
      python setup.py install

script:
    - flake8 --count hnn_core
    - py.test --cov=hnn_core --cov-report=xml hnn_core/tests/
after_success:
    - bash <(curl -s https://codecov.io/bash) -f ./coverage.xml
